global:
  domain: "staging.yas.local"
backoffice-bff:
  backend:
    service:
      type: NodePort
      nodePort: 30099
    ingress:
      enabled: true
      host: backoffice.staging.yas.local.com
      path: /
    image:
      repository: mk1505/yas-backoffice-bff
      tag: dev-cea6f449
storefront-bff:
  backend:
    service:
      type: NodePort
      nodePort: 30101
    ingress:
      enabled: true
      host: api.staging.yas.local.com
      path: /
      pathType: Prefix
    image:
      repository: mk1505/yas-storefront-bff
      tag: dev-cea6f449
swagger-ui:
  image:
    repository: swaggerapi/swagger-ui
    tag: v5.17.14
  urls: '[{ "url": "http://api.yas.local.com/api/product/v3/api-docs", "name": "Product" }, { "url": "http://api.yas.local.com/api/media/v3/api-docs", "name": "Media" }, { "url": "http://api.yas.local.com/api/customer/v3/api-docs", "name": "Customer" }, { "url": "http://api.yas.local.com/api/cart/v3/api-docs", "name": "Cart"}, { "url": "http://api.yas.local.com/api/rating/v3/api-docs", "name": "Rating" }, { "url": "http://api.yas.local.com/api/order/v3/api-docs", "name": "Order"}, { "url": "http://api.yas.local.com/api/payment/v3/api-docs", "name": "Payment"}, { "url": "http://api.yas.local.com/api/location/v3/api-docs", "name": "Location"}, { "url": "http://api.yas.local.com/api/inventory/v3/api-docs", "name": "Inventory"}, { "url": "http://api.yas.local.com/api/tax/v3/api-docs", "name": "Tax" }, { "url": "http://api.yas.local.com/api/promotion/v3/api-docs", "name": "Promotion"}, { "url": "http://api.yas.local.com/api/search/v3/api-docs", "name": "Search"}]'
  service:
    type: NodePort
    nodePort: 30102
  nodeSelector:
    kubernetes.io/arch: amd64
  ingress:
    enabled: false
cart:
  backend:
    service:
      type: NodePort
      nodePort: 30103
    ingress:
      enabled: false
    image:
      repository: mk1505/yas-cart
      tag: dev-8c0fed2a
customer:
  backend:
    service:
      type: NodePort
      nodePort: 30104
    ingress:
      enabled: false
    image:
      repository: mk1505/yas-customer
      tag: dev-8c0fed2a
inventory:
  backend:
    service:
      type: NodePort
      nodePort: 30105
    ingress:
      enabled: false
    image:
      repository: mk1505/yas-inventory
      tag: dev-8c0fed2a
location:
  backend:
    service:
      type: NodePort
      nodePort: 30106
    ingress:
      enabled: false
media:
  backend:
    service:
      type: NodePort
      nodePort: 30107
    ingress:
      enabled: false
    image:
      repository: mk1505/yas-media
      tag: dev-e84ba9a9
order:
  backend:
    service:
      type: NodePort
      nodePort: 30108
    ingress:
      enabled: false
    image:
      repository: mk1505/yas-order
      tag: dev-cea6f449
product:
  backend:
    service:
      type: NodePort
      nodePort: 30111
    ingress:
      enabled: false
    image:
      repository: mk1505/yas-product
      tag: dev-e7d9074f
search:
  backend:
    nodeSelector:
      kubernetes.io/arch: amd64
    service:
      type: NodePort
      nodePort: 30114
    ingress:
      enabled: false
    image:
      repository: mk1505/yas-search
      tag: dev-e7d9074f
tax:
  backend:
    service:
      type: NodePort
      nodePort: 30115
    ingress:
      enabled: false
    image:
      repository: mk1505/yas-tax
      tag: dev-e84ba9a9
webhook:
  backend:
    service:
      type: NodePort
      nodePort: 30117
    ingress:
      enabled: false
    image:
      repository: mk1505/yas-webhook
      tag: dev-e84ba9a9
sampledata:
  backend:
    service:
      type: NodePort
      nodePort: 30118
    ingress:
      enabled: false
    image:
      repository: mk1505/yas-sampledata
      tag: dev-e7d9074f
backoffice-ui:
  ui:
    image:
      repository: mk1505/yas-backoffice
      tag: 8dfc15b6
storefront-ui:
  ui:
    image:
      repository: mk1505/yas-storefront
      tag: 8dfc15b6
