# global:
#   domain: "yas-staging.local"

# backoffice-bff:
#   backend:
#     image:
#       repository: mk1505/yas-cart
#       tag: "467416e5"
#     service:
#       type: NodePort
#       nodePort: 300100
#     ingress:
#       enabled: false

# storefront-bff:
#   backend:
#     image:
#       repository: ghcr.io/nashtech-garage/yas-storefront-bff
#       tag: latest
#     service:
#       type: NodePort
#       nodePort: 30082
#     ingress:
#       enabled: false

# swagger-ui:
#   backend:
#     image:
#       repository: ghcr.io/nashtech-garage/yas-swagger-ui
#       tag: latest
#     service:
#       type: NodePort
#       nodePort: 30083
#     ingress:
#       enabled: false

# cart:
#   backend:
#     image:
#       repository: mk1505/yas-cart
#       tag: "467416e5"
#     service:
#       type: NodePort
#       nodePort: 30084
#     ingress:
#       enabled: false

# customer:
#   backend:
#     image:
#       repository: ghcr.io/nashtech-garage/yas-customer
#       tag: latest
#     service:
#       type: NodePort
#       nodePort: 30085
#     ingress:
#       enabled: false

# inventory:
#   backend:
#     image:
#       repository: ghcr.io/nashtech-garage/yas-inventory
#       tag: latest
#     service:
#       type: NodePort
#       nodePort: 30086
#     ingress:
#       enabled: false

# location:
#   backend:
#     image:
#       repository: ghcr.io/nashtech-garage/yas-location
#       tag: latest
#     service:
#       type: NodePort
#       nodePort: 30087
#     ingress:
#       enabled: false

# media:
#   backend:
#     image:
#       repository: ghcr.io/nashtech-garage/yas-media
#       tag: latest
#     service:
#       type: NodePort
#       nodePort: 30088
#     ingress:
#       enabled: false

# order:
#   backend:
#     image:
#       repository: ghcr.io/nashtech-garage/yas-order
#       tag: latest
#     service:
#       type: NodePort
#       nodePort: 30089
#     ingress:
#       enabled: false

# payment:
#   backend:
#     image:
#       repository: ghcr.io/nashtech-garage/yas-payment
#       tag: latest
#     service:
#       type: NodePort
#       nodePort: 30090
#     ingress:
#       enabled: false

# payment-paypal:
#   backend:
#     image:
#       repository: ghcr.io/nashtech-garage/yas-payment-paypal
#       tag: latest
#     service:
#       type: NodePort
#       nodePort: 30091
#     ingress:
#       enabled: false

# product:
#   backend:
#     image:
#       repository: ghcr.io/nashtech-garage/yas-product
#       tag: latest
#     service:
#       type: NodePort
#       nodePort: 30092
#     ingress:
#       enabled: false

# promotion:
#   backend:
#     image:
#       repository: ghcr.io/nashtech-garage/yas-promotion
#       tag: latest
#     service:
#       type: NodePort
#       nodePort: 30093
#     ingress:
#       enabled: false

# rating:
#   backend:
#     image:
#       repository: ghcr.io/nashtech-garage/yas-rating
#       tag: latest
#     service:
#       type: NodePort
#       nodePort: 30094
#     ingress:
#       enabled: false

# search:
#   backend:
#     image:
#       repository: ghcr.io/nashtech-garage/yas-search
#       tag: latest
#     service:
#       type: NodePort
#       nodePort: 30095
#     ingress:
#       enabled: false

# tax:
#   backend:
#     image:
#       repository: ghcr.io/nashtech-garage/yas-tax
#       tag: latest
#     service:
#       type: NodePort
#       nodePort: 30096
#     ingress:
#       enabled: false

# recommendation:
#   backend:
#     image:
#       repository: ghcr.io/nashtech-garage/yas-recommendation
#       tag: latest
#     service:
#       type: NodePort
#       nodePort: 30097
#     ingress:
#       enabled: false

# webhook:
#   backend:
#     image:
#       repository: ghcr.io/nashtech-garage/yas-webhook
#       tag: latest
#     service:
#       type: NodePort
#       nodePort: 30098
#     ingress:
#       enabled: false

# sampledata:
#   backend:
#     image:
#       repository: ghcr.io/nashtech-garage/yas-sampledata
#       tag: latest
#     service:
#       type: NodePort
#       nodePort: 30099
#     ingress:
#       enabled: false