apiVersion: v2
name: yas-umbrella
description: An Umbrella Helm chart for deploying Yas microservices and frontends
type: application
version: 0.1.0
appVersion: "latest"

dependencies:
  - name: yas-configuration
    version: ">=0.0.0-0"
    repository: file://../yas/k8s/charts/yas-configuration
  - name: backoffice-bff
    version: ">=0.0.0-0"
    repository: file://../yas/k8s/charts/backoffice-bff
  - name: backoffice-ui
    version: ">=0.0.0-0"
    repository: file://../yas/k8s/charts/backoffice-ui
  - name: storefront-bff
    version: ">=0.0.0-0"
    repository: file://../yas/k8s/charts/storefront-bff
  - name: storefront-ui
    version: ">=0.0.0-0"
    repository: file://../yas/k8s/charts/storefront-ui
  - name: swagger-ui
    version: ">=0.0.0-0"
    repository: file://../yas/k8s/charts/swagger-ui
  - name: cart
    version: ">=0.0.0-0"
    repository: file://../yas/k8s/charts/cart
  - name: customer
    version: ">=0.0.0-0"
    repository: file://../yas/k8s/charts/customer
  - name: inventory
    version: ">=0.0.0-0"
    repository: file://../yas/k8s/charts/inventory
  - name: media
    version: ">=0.0.0-0"
    repository: file://../yas/k8s/charts/media
  - name: order
    version: ">=0.0.0-0"
    repository: file://../yas/k8s/charts/order
  - name: product
    version: ">=0.0.0-0"
    repository: file://../yas/k8s/charts/product
  - name: search
    version: ">=0.0.0-0"
    repository: file://../yas/k8s/charts/search
  - name: tax
    version: ">=0.0.0-0"
    repository: file://../yas/k8s/charts/tax
  # - name: sampledata
  #   version: ">=0.0.0-0"
  #   repository: file://../yas/k8s/charts/sampledata
