apiVersion: v2
name: yas-umbrella
description: An Umbrella Helm chart for deploying Yas microservices and frontends
type: application
version: 0.1.0
appVersion: "latest"

dependencies:
  - name: yas-configuration
    version: ">=0.0.0-0"
    repository: file://../yas/k8s/charts/yas-configuration
  # - name: backoffice-bff
  #   version: ">=0.0.0-0"
  #   repository: file://../yas/k8s/charts/backoffice-bff
  # - name: backoffice-ui
  #   version: ">=0.0.0-0"
  #   repository: file://../yas/k8s/charts/backoffice-ui
  - name: storefront-bff
    version: ">=0.0.0-0"
    repository: file://../yas/k8s/charts/storefront-bff
  # - name: storefront-ui
  #   version: ">=0.0.0-0"
  #   repository: file://../yas/k8s/charts/storefront-ui
  - name: swagger-ui
    version: ">=0.0.0-0"
    repository: file://../yas/k8s/charts/swagger-ui
  - name: cart
    version: ">=0.0.0-0"
    repository: file://../yas/k8s/charts/cart
  # - name: customer
  #   version: ">=0.0.0-0"
  #   repository: file://../yas/k8s/charts/customer
  # - name: inventory
  #   version: ">=0.0.0-0"
  #   repository: file://../yas/k8s/charts/inventory
  # - name: location
  #   version: ">=0.0.0-0"
  #   repository: file://../yas/k8s/charts/location
  # - name: media
  #   version: ">=0.0.0-0"
  #   repository: file://../yas/k8s/charts/media
  # - name: order
  #   version: ">=0.0.0-0"
  #   repository: file://../yas/k8s/charts/order
  # - name: payment
  #   version: ">=0.0.0-0"
  #   repository: file://../yas/k8s/charts/payment
  # - name: payment-paypal
  #   version: ">=0.0.0-0"
  #   repository: file://../yas/k8s/charts/payment-paypal
  # - name: product
  #   version: ">=0.0.0-0"
  #   repository: file://../yas/k8s/charts/product
  # - name: promotion
  #   version: ">=0.0.0-0"
  #   repository: file://../yas/k8s/charts/promotion
  # - name: rating
  #   version: ">=0.0.0-0"
  #   repository: file://../yas/k8s/charts/rating
  # - name: search
  #   version: ">=0.0.0-0"
  #   repository: file://../yas/k8s/charts/search
  # - name: tax
  #   version: ">=0.0.0-0"
  #   repository: file://../yas/k8s/charts/tax
  # - name: recommendation
  #   version: ">=0.0.0-0"
  #   repository: file://../yas/k8s/charts/recommendation
  # - name: webhook
  #   version: ">=0.0.0-0"
  #   repository: file://../yas/k8s/charts/webhook
  # - name: sampledata
  #   version: ">=0.0.0-0"
  #   repository: file://../yas/k8s/charts/sampledata
