apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yas-istio-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/Intro-to-DevOps/GitOps.git"
    targetRevision: release
    path: staging/istio
  destination:
    server: https://kubernetes.default.svc
    namespace: yas-staging
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
