apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: deny-all
  namespace: yas-staging
spec:
  action: DENY
  rules:
  - from:
    - source:
        notPrincipals: ["cluster.local/ns/yas-staging/sa/*"]
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-internal
  namespace: yas-staging
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
          - "cluster.local/ns/yas-staging/sa/cart"
          - "cluster.local/ns/yas-staging/sa/order"
          - "cluster.local/ns/yas-staging/sa/product"
          - "cluster.local/ns/yas-staging/sa/customer"
          - "cluster.local/ns/yas-staging/sa/inventory"
          - "cluster.local/ns/yas-staging/sa/tax"
          - "cluster.local/ns/yas-staging/sa/media"
          - "cluster.local/ns/yas-staging/sa/search"
          - "cluster.local/ns/yas-staging/sa/storefront-bff"
          - "cluster.local/ns/yas-staging/sa/backoffice-bff"
          - "cluster.local/ns/yas-staging/sa/rating"
          - "cluster.local/ns/yas-staging/sa/promotion"
          - "cluster.local/ns/yas-staging/sa/payment"
          - "cluster.local/ns/yas-staging/sa/payment-paypal"
          - "cluster.local/ns/yas-staging/sa/recommendation"
          - "cluster.local/ns/yas-staging/sa/webhook"
