apiVersion: v1
kind: Secret
metadata:
  name: yas-db-secret
  namespace: yas-dev
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
data:
  POSTGRES_USER: YWRtaW4=
  POSTGRES_PASSWORD: YWRtaW4=

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: yas-global-config
data:
  SERVER_PORT: "80"
  SPRING_PROFILES_ACTIVE: "prod"
  
  OTEL_JAVAAGENT_ENABLED: "false"
  JAVA_TOOL_OPTIONS: ""
  
  KAFKA_SERVICE_HOST: "kafka"
  KAFKA_SERVICE_PORT: "9092"
  SPRING_DATA_REDIS_HOST: "redis"
  SPRING_DATA_REDIS_PORT: "6379"
  
  YAS_PRICE_INCLUDES_TAX: "false"
  YAS_CURRENCY_UNIT: "VND"
  YAS_PUBLIC_API_URL: "http://api.yas.local"
  
  YAS_SERVICES_CART: "http://cart/cart"
  YAS_SERVICES_CUSTOMER: "http://customer/customer"
  YAS_SERVICES_PRODUCT: "http://product/product"
  YAS_SERVICES_TAX: "http://tax/tax"
  YAS_SERVICES_ORDER: "http://order/order"
  YAS_SERVICES_PAYMENT: "http://payment/payment"
  YAS_SERVICES_LOCATION: "http://location/location"
  YAS_SERVICES_MEDIA: "http://media/media"
  YAS_SERVICES_PROMOTION: "http://promotion/promotion"
  YAS_SERVICES_INVENTORY: "http://inventory/inventory"
  YAS_SERVICES_RATING: "http://rating/rating"
  YAS_SERVICES_SAMPLE_DATA: "http://sampledata/sampledata"
  YAS_SERVICES_RECOMMENDATION: "http://recommendation/recommendation"