global:
  domain: "yas.local"

backoffice-bff:
  backend:
    service:
      type: NodePort
      nodePort: 30100

storefront-bff:
  backend:
    service:
      type: NodePort
      nodePort: 30082

swagger-ui:
  service:
    type: NodePort
    nodePort: 30083

cart:
  backend:
    service:
      type: NodePort
      nodePort: 30084

customer:
  backend:
    service:
      type: NodePort
      nodePort: 30085

inventory:
  backend:
    service:
      type: NodePort
      nodePort: 30086

location:
  backend:
    service:
      type: NodePort
      nodePort: 30087

media:
  backend:
    service:
      type: NodePort
      nodePort: 30088

order:
  backend:
    service:
      type: NodePort
      nodePort: 30089

payment:
  backend:
    service:
      type: NodePort
      nodePort: 30090

payment-paypal:
  backend:
    service:
      type: NodePort
      nodePort: 30091

product:
  backend:
    service:
      type: NodePort
      nodePort: 30092

promotion:
  backend:
    service:
      type: NodePort
      nodePort: 30093

rating:
  backend:
    service:
      type: NodePort
      nodePort: 30094

search:
  backend:
    service:
      type: NodePort
      nodePort: 30095

tax:
  backend:
    service:
      type: NodePort
      nodePort: 30096

recommendation:
  backend:
    service:
      type: NodePort
      nodePort: 30097

webhook:
  backend:
    service:
      type: NodePort
      nodePort: 30098

sampledata:
  backend:
    service:
      type: NodePort
      nodePort: 30099