global:
  domain: "yas.local"
backoffice-bff:
  backend:
    service:
      type: NodePort
      nodePort: 30200
    ingress:
      enabled: true
    image:
      repository: mk1505/yas-backoffice-bff
      tag: edad0f36
storefront-bff:
  backend:
    service:
      type: NodePort
      nodePort: 30201
    ingress:
      enabled: true
      className: nginx
      host: api.yas.local.com
      path: /
      pathType: Prefix
    image:
      repository: mk1505/yas-storefront-bff
      tag: ba0e8e64
swagger-ui:
  urls: "[{ url: 'http://api.yas.local.com/api/product/v3/api-docs', name: 'Product' }, { url: 'http://api.yas.local.com/api/media/v3/api-docs', name: 'Media' }, { url: 'http://api.yas.local.com/api/customer/v3/api-docs', name: 'Customer' }, { url: 'http://api.yas.local.com/api/cart/v3/api-docs', name: 'Cart'}, { url: 'http://api.yas.local.com/api/rating/v3/api-docs', name: 'Rating' }, { url: 'http://api.yas.local.com/api/order/v3/api-docs', name: 'Order'}, { url: 'http://api.yas.local.com/api/payment/v3/api-docs', name: 'Payment'}, { url: 'http://api.yas.local.com/api/location/v3/api-docs', name: 'Location'}, { url: 'http://api.yas.local.com/api/inventory/v3/api-docs', name: 'Inventory'}, { url: 'http://api.yas.local.com/api/tax/v3/api-docs', name: 'Tax' }, { url: 'http://api.yas.local.com/api/promotion/v3/api-docs', name: 'Promotion'}, { url: 'http://api.yas.local.com/api/search/v3/api-docs', name: 'Search'}]"
  service:
    type: NodePort
    nodePort: 30202
  ingress:
    enabled: true
cart:
  backend:
    service:
      type: NodePort
      nodePort: 30203
    ingress:
      enabled: true
    image:
      repository: mk1505/yas-cart
      tag: dev-d7ce1edf
customer:
  backend:
    service:
      type: NodePort
      nodePort: 30204
    ingress:
      enabled: true
    image:
      repository: mk1505/yas-customer
      tag: ba0e8e64
inventory:
  backend:
    service:
      type: NodePort
      nodePort: 30205
    ingress:
      enabled: true
    image:
      repository: mk1505/yas-inventory
      tag: edad0f36
location:
  backend:
    service:
      type: NodePort
      nodePort: 30206
    ingress:
      enabled: true
media:
  backend:
    service:
      type: NodePort
      nodePort: 30207
    ingress:
      enabled: true
    image:
      repository: mk1505/yas-media
      tag: edad0f36
order:
  backend:
    service:
      type: NodePort
      nodePort: 30208
    ingress:
      enabled: true
    image:
      repository: mk1505/yas-order
      tag: edad0f36
product:
  backend:
    service:
      type: NodePort
      nodePort: 30211
    ingress:
      enabled: true
    image:
      repository: mk1505/yas-product
      tag: edad0f36
search:
  backend:
    service:
      type: NodePort
      nodePort: 30214
    ingress:
      enabled: true
    image:
      repository: mk1505/yas-search
      tag: edad0f36
tax:
  backend:
    service:
      type: NodePort
      nodePort: 30215
    ingress:
      enabled: true
    image:
      repository: mk1505/yas-tax
      tag: edad0f36
webhook:
  backend:
    service:
      type: NodePort
      nodePort: 30217
    ingress:
      enabled: true
sampledata:
  backend:
    service:
      type: NodePort
      nodePort: 30218
    ingress:
      enabled: true
    image:
      repository: mk1505/yas-sampledata
      tag: edad0f36
backoffice-ui:
  ui:
    image:
      repository: mk1505/yas-backoffice
      tag: 8dfc15b6
storefront-ui:
  ui:
    image:
      repository: mk1505/yas-storefront
      tag: 8dfc15b6
