apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  labels:
    app: cart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
        - name: cart
          image: ghcr.io/nashtech-garage/yas-cart:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "512Mi"
          envFrom:
            - configMapRef:
                name: yas-global-config
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/cart"
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: "/cart"
            - name: OTEL_SERVICE_NAME
              value: "cart-service"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: yas-db-secret
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: yas-db-secret
                  key: POSTGRES_PASSWORD