apiVersion: apps/v1
kind: Deployment
metadata:
  name: storefront
  labels:
    app: storefront
  namespace: yas-dev
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storefront
  template:
    metadata:
      labels:
        app: storefront
    spec:
      containers:
        - name: storefront
          image: ghcr.io/nashtech-garage/yas-storefront:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "300m"
          envFrom:
            - configMapRef:
                name: yas-global-config
          env:
            - name: PORT
              value: "3000"
            - name: NEXT_PUBLIC_API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: yas-global-config
                  key: YAS_PUBLIC_API_URL
            - name: NODE_ENV
              value: "production"
            - name: HOSTNAME
              value: "0.0.0.0"