apiVersion: v1
kind: Service
metadata:
  name: storefront
  labels:
    app: storefront
  namespace: yas-dev
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  type: NodePort
  selector:
    app: storefront
  ports:
    - port: 3000       
      targetPort: 3000 
      nodePort: 30080 