apiVersion: apps/v1
kind: Deployment
metadata:
  name: storefront-bff
  labels:
    app: storefront-bff
  namespace: yas-dev
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 1 # Giữ 1 replica để tiết kiệm tài nguyên hệ thống
  selector:
    matchLabels:
      app: storefront-bff
  template:
    metadata:
      labels:
        app: storefront-bff
    spec:
      containers:
        - name: storefront-bff
          image: ghcr.io/nashtech-garage/yas-storefront-bff:latest # Điểm để Jenkins cập nhật tag commit khi CD
          ports:
            - containerPort: 80
          # Giới hạn tài nguyên nghiêm ngặt cho cụm VM 16GB
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          # Kế thừa toàn bộ bản đồ routing (URL của các service khác) từ ConfigMap chung
          envFrom:
            - configMapRef:
                name: yas-global-config
          env:
            - name: OTEL_SERVICE_NAME
              value: "storefront-bff"
            # Cấu hình Keycloak Client cho BFF nếu cần (đọc từ config chung hoặc khai báo trực tiếp)
            - name: KEYCLOAK_INIT_REALM
              value: "yas"