apiVersion: v1
kind: Service
metadata:
  name: storefront-bff
  labels:
    app: storefront-bff
  namespace: yas-dev
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  type: NodePort # Dùng NodePort để Frontend từ ngoài Internet (hoặc máy cá nhân của team) gọi vào được
  selector:
    app: storefront-bff
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30081 # Đặt cổng 30081 (ngay sau cổng 30080 của Storefront để dễ quản lý)