apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yas-storefront-bff
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://nashtech-garage.github.io/yas/
    chart: storefront-bff
    targetRevision: 0.1.0
    helm:
      values: |
        backend:
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: YAS_SERVICES_CUSTOMER
              value: "http://yas-customer/customer"
            - name: YAS_SERVICES_CART
              value: "http://yas-cart/cart"
            - name: YAS_SERVICES_RATING
              value: "http://yas-rating/rating"
            - name: YAS_SERVICES_ORDER
              value: "http://yas-order/order"
            - name: YAS_SERVICES_LOCATION
              value: "http://yas-location/location"
            - name: YAS_SERVICES_INVENTORY
              value: "http://yas-inventory/inventory"
            - name: YAS_SERVICES_TAX
              value: "http://yas-tax/tax"
            - name: YAS_SERVICES_PROMOTION
              value: "http://yas-promotion/promotion"
            - name: YAS_SERVICES_PAYMENT
              value: "http://yas-payment/payment"
            - name: YAS_SERVICES_SAMPLE_DATA
              value: "http://yas-sampledata/sampledata"
            - name: SERVER_PORT
              value: "80"
            - name: LOGGING_CONFIG
              value: "/app-config/logback-spring.xml"
            - name: JAVA_TOOL_OPTIONS
              value: "-javaagent:opentelemetry-javaagent.jar"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://collector:5555"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "grpc"
            - name: OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
              value: "cumulative"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.namespace=yas-msa"
            - name: OTEL_SERVICE_NAME
              value: "storefront-bff-service"
            - name: OTEL_LOGS_EXPORTER
              value: "otlp"
            - name: OTEL_TRACES_EXPORTER
              value: "otlp"
            - name: OTEL_METRICS_EXPORTER
              value: "otlp"
            - name: OTEL_INSTRUMENTATION_LOGBACK-MDC_ADD-BAGGAGE
              value: "true"
            - name: OTEL_JAVAAGENT_LOGGING
              value: "application"
            - name: OTEL_JAVAAGENT_ENABLED
              value: "true"
            - name: OTEL_JAVAAGENT_DEBUG
              value: "false"
  destination:
    server: https://kubernetes.default.svc
    namespace: yas-dev
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true