apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  namespace: yas-dev
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app: product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: ghcr.io/nashtech-garage/yas-product:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "512Mi"
          envFrom:
            - configMapRef:
                name: yas-global-config
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/product"
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: "/product"
            - name: OTEL_SERVICE_NAME
              value: "product-service"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: yas-db-secret
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: yas-db-secret
                  key: POSTGRES_PASSWORD