---
# Source: yas-configuration/charts/reloader/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-namespace: "yas-dev"
    meta.helm.sh/release-name: "yas-configuration"
  labels:
    app: yas-reloader
    chart: "reloader-1.0.29"
    release: "yas-configuration"
    heritage: "Helm"
    app.kubernetes.io/managed-by: "Helm"
  name: yas-reloader
  namespace: yas-dev
---
# Source: yas-configuration/templates/yas-credentials.secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: yas-postgresql-credentials-secret
  annotations:
    reloader.stakater.com/match: "true"
type: Opaque
data:
  POSTGRESQL_USERNAME: eWFzYWRtaW51c2Vy
  POSTGRESQL_PASSWORD: YWRtaW4=
---
# Source: yas-configuration/templates/yas-credentials.secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: yas-elasticsearch-credentials-secret
  annotations:
    reloader.stakater.com/match: "true"
type: Opaque
data:
  ELASTICSEARCH_USERNAME: eWFz
  ELASTICSEARCH_PASSWORD: TGFyVW1CM0E0OU5UZzlZbWdXND0=
---
# Source: yas-configuration/templates/yas-credentials.secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: yas-keycloak-credentials-secret
  annotations:
    reloader.stakater.com/match: "true"
type: Opaque
data:
  KEYCLOAK_BACKOFFICE_BFF_CLIENT_SECRET: VFZhY0xDMGNROHRpaUVLaVRWZXJUYjJZdndRMVRSSkY=
  KEYCLOAK_STOREFRONT_BFF_CLIENT_SECRET: WnJVOUkwcTJ1WEJnbEJubXZ5SmRrbDFsZjBuY3I4dG4=
  KEYCLOAK_CUSTOMER_MANAGEMENT_CLIENT_SECRET: TktBcjNybmp3bTlqbGFrZ0twZWx1a1pHRmFIWXFJV0U=
---
# Source: yas-configuration/templates/yas-credentials.secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: yas-redis-credentials-secret
  annotations:
    reloader.stakater.com/match: "true"
type: Opaque
data:
  REDIS_PASSWORD: cmVkaXM=
---
# Source: yas-configuration/templates/yas-credentials.secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: yas-openai-api-key-secret
  annotations:
    reloader.stakater.com/match: "true"
type: Opaque
data:
  OPENAI_API_KEY: dXBkYXRlLW1l
---
# Source: yas-configuration/templates/yas-configurations.configmap.yaml
#Configmap of general application config for all microservices
apiVersion: v1
kind: ConfigMap
metadata:
  name: yas-configuration-configmap
  annotations:
    reloader.stakater.com/match: "true"
data:
  application.yaml: |
    logging:
      pattern:
        level: application=${spring.application.name} traceId=%X{traceId:-} spanId=%X{spanId:-}
          level=%level
    management:
      endpoint:
        health:
          probes:
            enabled: true
          show-details: always
      endpoints:
        web:
          exposure:
            include: prometheus, health
      health:
        livenessstate:
          enabled: true
        readinessstate:
          enabled: true
      metrics:
        tags:
          application: ${spring.application.name}
      otlp:
        tracing:
          endpoint: http://opentelemetry-collector.observability:4318/v1/traces
      server:
        port: 8090
      tracing:
        sampling:
          probability: 1
    server:
      port: 80
      shutdown: graceful
    spring:
      datasource:
        password: ${POSTGRESQL_PASSWORD}
        url: null
        username: ${POSTGRESQL_USERNAME}
      kafka:
        bootstrap-servers: kafka-cluster-kafka-brokers.kafka:9092
        consumer:
          bootstrap-servers: kafka-cluster-kafka-brokers.kafka:9092
      lifecycle:
        timeout-per-shutdown-phase: 30s
      security:
        oauth2:
          resourceserver:
            jwt:
              issuer-uri: http://identity.yas.local.com/realms/Yas
    springdoc:
      oauthflow:
        authorization-url: http://identity.yas.local.com/realms/Yas/protocol/openid-connect/auth
        token-url: http://identity.yas.local.com/realms/Yas/protocol/openid-connect/token
    yas:
      services:
        cart: http://cart/cart
        customer: http://customer/customer
        inventory: http://inventory/inventory
        location: http://location/location
        media: http://media/media
        order: http://order/order
        payment: http://payment/payment
        payment-paypal: http://payment-paypal/payment-paypal
        product: http://product/product
        promotion: http://promotion/promotion
        rating: http://rating/rating
        recommendation: http://recommendation/recommendation
        sampledata: http://sampledata/sampledata
        search: http://search/search
        tax: http://tax/tax
  logback.xml: |
    <?xml version="1.0" encoding="UTF-8" ?>
    <Configuration>
        <include resource="org/springframework/boot/logging/logback/defaults.xml" />
        <include resource="org/springframework/boot/logging/logback/console-appender.xml" />
        <property name="LOG_LEVEL" value="${LOG_LEVEL:-INFO}"/>
        <root level="INFO">
            <appender-ref ref="CONSOLE" />
        </root>
        <logger name="com.yas" level="${LOG_LEVEL}" additivity="false">
            <appender-ref ref="CONSOLE" />
        </logger>
    </Configuration>
---
# Source: yas-configuration/templates/yas-configurations.configmap.yaml
#Configmap of gateway routes config for bff microservices
apiVersion: v1
kind: ConfigMap
metadata:
  name: yas-gateway-routes-config-configmap
  annotations:
    reloader.stakater.com/match: "true"
data:
  gateway-routes-config.yaml: |
    spring:
      cloud:
        gateway:
          routes:
          - filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
            - TokenRelay=
            id: product_api
            predicates:
            - Path=/api/product/**
            uri: http://product
          - filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
            - TokenRelay=
            id: location_api
            predicates:
            - Path=/api/location/**
            uri: http://location
          - filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
            - TokenRelay=
            id: inventory_api
            predicates:
            - Path=/api/inventory/**
            uri: http://inventory
          - filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
            - TokenRelay=
            id: cart_api
            predicates:
            - Path=/api/cart/**
            uri: http://cart
          - filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
            - TokenRelay=
            id: customer_api
            predicates:
            - Path=/api/customer/**
            uri: http://customer
          - filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
            - TokenRelay=
            id: media_api
            predicates:
            - Path=/api/media/**
            uri: http://media
          - filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
            - TokenRelay=
            id: rating_api
            predicates:
            - Path=/api/rating/**
            uri: http://rating
          - filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
            - TokenRelay=
            id: tax_api
            predicates:
            - Path=/api/tax/**
            uri: http://tax
          - filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
            - TokenRelay=
            id: promotion_api
            predicates:
            - Path=/api/promotion/**
            uri: http://protion
          - filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
            - TokenRelay=
            id: search_api
            predicates:
            - Path=/api/search/**
            uri: http://search
          - filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
            - TokenRelay=
            id: order_api
            predicates:
            - Path=/api/order/**
            uri: http://order
          - filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
            - TokenRelay=
            id: recommendation_api
            predicates:
            - Path=/api/recommendation/**
            uri: http://recommendation
          - filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
            - TokenRelay=
            id: webhook_api
            predicates:
            - Path=/api/webhook/**
            uri: http://webhook
          - filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
            - TokenRelay=
            id: sampledata_api
            predicates:
            - Path=/api/sampledata/**
            uri: http://sampledata
          - id: ui
            predicates:
            - Path=/**
            uri: ${UI_HOST}
---
# Source: yas-configuration/templates/yas-configurations.configmap.yaml
#Configmap for backoffice-bff extra
apiVersion: v1
kind: ConfigMap
metadata:
  name: backoffice-bff-extra-configmap
  annotations:
    reloader.stakater.com/match: "true"
data:
  backoffice-bff-extra-config.yaml: |
    spring:
      data:
        redis:
          host: redis-master.redis
          password: ${REDIS_PASSWORD}
          port: 6379
      security:
        oauth2:
          client:
            provider:
              keycloak:
                issuer-uri: http://identity.yas.local.com/realms/Yas
            registration:
              api-client:
                client-id: backoffice-bff
                client-secret: ${KEYCLOAK_BACKOFFICE_BFF_CLIENT_SECRET}
                provider: keycloak
                scope: openid, profile, email, roles
---
# Source: yas-configuration/templates/yas-configurations.configmap.yaml
#Configmap for storefront-bff extra
apiVersion: v1
kind: ConfigMap
metadata:
  name: storefront-bff-extra-configmap
  annotations:
    reloader.stakater.com/match: "true"
data:
  storefront-bff-extra-config.yaml: |
    spring:
      data:
        redis:
          host: redis-master.redis
          password: ${REDIS_PASSWORD}
          port: 6379
      security:
        oauth2:
          client:
            provider:
              keycloak:
                issuer-uri: http://identity.yas.local.com/realms/Yas
            registration:
              api-client:
                client-id: storefront-bff
                client-secret: ${KEYCLOAK_STOREFRONT_BFF_CLIENT_SECRET}
                provider: keycloak
                scope: openid, profile, email, roles
---
# Source: yas-configuration/templates/yas-configurations.configmap.yaml
# Configmap for media application config custom
apiVersion: v1
kind: ConfigMap
metadata:
  name: media-application-configmap
  annotations:
    reloader.stakater.com/match: "true"
data:
  media-application.yaml: |
    server:
      servlet:
        context-path: /media
    yas:
      publicUrl: http://api.yas.local.com/media
---
# Source: yas-configuration/templates/yas-configurations.configmap.yaml
#Configmap for customer application config custom
apiVersion: v1
kind: ConfigMap
metadata:
  name: customer-application-configmap
  annotations:
    reloader.stakater.com/match: "true"
data:
  customer-application.yaml: |
    
    keycloak:
      auth-server-url: http://identity.yas.local.com
      credentials:
        secret: ${KEYCLOAK_CUSTOMER_MANAGEMENT_CLIENT_SECRET}
      realm: Yas
      resource: customer-management
---
# Source: yas-configuration/templates/yas-configurations.configmap.yaml
# Configmap of search application config custom
apiVersion: v1
kind: ConfigMap
metadata:
  name: search-application-configmap
  annotations:
    reloader.stakater.com/match: "true"
data:
  search-application.yaml: |
    
    elasticsearch:
      password: ${ELASTICSEARCH_PASSWORD}
      url: elasticsearch-es-http.elasticsearch
      username: ${ELASTICSEARCH_USERNAME}
---
# Source: yas-configuration/templates/yas-configurations.configmap.yaml
# Configmap of cart application config custom
apiVersion: v1
kind: ConfigMap
metadata:
  name: cart-application-configmap
  annotations:
    reloader.stakater.com/match: "true"
data:
  cart-application.yaml: |
    
    null
---
# Source: yas-configuration/templates/yas-configurations.configmap.yaml
# Configmap of order application config custom
apiVersion: v1
kind: ConfigMap
metadata:
  name: order-application-configmap
  annotations:
    reloader.stakater.com/match: "true"
data:
  order-application.yaml: |
    
    null
---
# Source: yas-configuration/templates/yas-configurations.configmap.yaml
# Configmap of payment application config custom
apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-application-configmap
  annotations:
    reloader.stakater.com/match: "true"
data:
  payment-application.yaml: |
    
    null
---
# Source: yas-configuration/templates/yas-configurations.configmap.yaml
# Configmap of payment-paypal application config custom
apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-paypal-application-configmap
  annotations:
    reloader.stakater.com/match: "true"
data:
  payment-paypal-application.yaml: |
    
    yas:
      public:
        url: http://storefront.yas.local.com/complete-payment
---
# Source: yas-configuration/templates/yas-configurations.configmap.yaml
# Configmap of production application config custom
apiVersion: v1
kind: ConfigMap
metadata:
  name: product-application-configmap
  annotations:
    reloader.stakater.com/match: "true"
data:
  product-application.yaml: |
    
    null
---
# Source: yas-configuration/templates/yas-configurations.configmap.yaml
# Configmap of recommendation application config custom
apiVersion: v1
kind: ConfigMap
metadata:
  name: recommendation-application-configmap
  annotations:
    reloader.stakater.com/match: "true"
data:
  recommendation-application.yaml: |
    
    spring:
      ai:
        azure:
          openai:
            api-key: ${OPENAI_API_KEY}
            embedding:
              options:
                model: text-embedding-3-small
            endpoint: https://product-recommendation.openai.azure.com
---
# Source: yas-configuration/templates/yas-configurations.configmap.yaml
# Configmap of sampledata application config custom
apiVersion: v1
kind: ConfigMap
metadata:
  name: sampledata-application-configmap
  annotations:
    reloader.stakater.com/match: "true"
data:
  sampledata-application.yaml: |
    
    spring:
      datasource:
        media:
          url: jdbc:postgresql://postgresql.postgres:5432/media
        product:
          url: jdbc:postgresql://postgresql.postgres:5432/product
---
# Source: yas-configuration/charts/reloader/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1

kind: Role
metadata:
  annotations:
    meta.helm.sh/release-namespace: "yas-dev"
    meta.helm.sh/release-name: "yas-configuration"
  labels:
    app: yas-reloader
    chart: "reloader-1.0.29"
    release: "yas-configuration"
    heritage: "Helm"
    app.kubernetes.io/managed-by: "Helm"
  name: yas-reloader-role
  namespace: yas-dev
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - configmaps
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - "apps"
    resources:
      - deployments
      - daemonsets
      - statefulsets
    verbs:
      - list
      - get
      - update
      - patch
  - apiGroups:
      - "extensions"
    resources:
      - deployments
      - daemonsets
    verbs:
      - list
      - get
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
---
# Source: yas-configuration/charts/reloader/templates/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1

kind: RoleBinding
metadata:
  annotations:
    meta.helm.sh/release-namespace: "yas-dev"
    meta.helm.sh/release-name: "yas-configuration"
  labels:
    app: yas-reloader
    chart: "reloader-1.0.29"
    release: "yas-configuration"
    heritage: "Helm"
    app.kubernetes.io/managed-by: "Helm"
  name: yas-reloader-role-binding
  namespace: yas-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: yas-reloader-role
subjects:
  - kind: ServiceAccount
    name: yas-reloader
    namespace: yas-dev
---
# Source: yas-configuration/charts/reloader/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    meta.helm.sh/release-namespace: "yas-dev"
    meta.helm.sh/release-name: "yas-configuration"
  labels:
    app: yas-reloader
    chart: "reloader-1.0.29"
    release: "yas-configuration"
    heritage: "Helm"
    app.kubernetes.io/managed-by: "Helm"
    group: com.stakater.platform
    provider: stakater
    version: v1.0.29
  name: yas-reloader
  namespace: yas-dev
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: yas-reloader
      release: "yas-configuration"
  template:
    metadata:
      labels:
        app: yas-reloader
        chart: "reloader-1.0.29"
        release: "yas-configuration"
        heritage: "Helm"
        app.kubernetes.io/managed-by: "Helm"
        group: com.stakater.platform
        provider: stakater
        version: v1.0.29
    spec:
      containers:
      - image: "ghcr.io/stakater/reloader:v1.0.29"
        imagePullPolicy: IfNotPresent
        name: yas-reloader
        env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace

        ports:
        - name: http
          containerPort: 9090
        livenessProbe:
          httpGet:
            path: /live
            port: http
          timeoutSeconds: 5
          failureThreshold: 5
          periodSeconds: 10
          successThreshold: 1
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: /metrics
            port: http
          timeoutSeconds: 5
          failureThreshold: 5
          periodSeconds: 10
          successThreshold: 1
          initialDelaySeconds: 10

        securityContext:
          {}
      securityContext: 
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: yas-reloader
