apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampledata
  namespace: yas-dev
  labels:
    app: sampledata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sampledata
  template:
    metadata:
      labels:
        app: sampledata
    spec:
      containers:
      - name: sampledata
        image: ghcr.io/nashtech-garage/yas-sampledata:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
          limits:
            memory: 512Mi
            cpu: 500m
        envFrom:
        - configMapRef:
            name: yas-global-config
        env:
        - name: SPRING_DATASOURCE_PRODUCT_URL
          value: jdbc:postgresql://postgres:5432/product
        - name: SPRING_DATASOURCE_MEDIA_URL
          value: jdbc:postgresql://postgres:5432/media
        - name: SERVER_SERVLET_CONTEXT_PATH
          value: /sampledata
        - name: YAS_PUBLIC_URL
          value: http://api.yas.local.com/sampledata
        - name: YAS_SERVICES_SAMPLE_DATA
          value: http://yas-sampledata/sampledata
        - name: SERVER_PORT
          value: '80'
        - name: LOGGING_CONFIG
          value: /app-config/logback-spring.xml
        - name: JAVA_TOOL_OPTIONS
          value: -javaagent:opentelemetry-javaagent.jar
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://collector:5555
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: grpc
        - name: OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
          value: cumulative
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: service.namespace=yas-msa
        - name: OTEL_SERVICE_NAME
          value: sampledata-service
        - name: OTEL_LOGS_EXPORTER
          value: otlp
        - name: OTEL_TRACES_EXPORTER
          value: otlp
        - name: OTEL_METRICS_EXPORTER
          value: otlp
        - name: OTEL_INSTRUMENTATION_LOGBACK-MDC_ADD-BAGGAGE
          value: 'true'
        - name: OTEL_JAVAAGENT_LOGGING
          value: application
        - name: OTEL_JAVAAGENT_ENABLED
          value: 'true'
        - name: OTEL_JAVAAGENT_DEBUG
          value: 'false'
