apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  namespace: yas-dev
  labels:
    app: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order
        image: ghcr.io/nashtech-garage/yas-order:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
          limits:
            memory: 512Mi
            cpu: 500m
        envFrom:
        - configMapRef:
            name: yas-global-config
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://postgres:5432/order
        - name: SERVER_SERVLET_CONTEXT_PATH
          value: /order
        - name: YAS_PUBLIC_URL
          value: http://api.yas.local.com/order
        - name: YAS_SERVICES_CART
          value: http://yas-cart/cart
        - name: YAS_SERVICES_CUSTOMER
          value: http://yas-customer/customer
        - name: YAS_SERVICES_PRODUCT
          value: http://yas-product/product
        - name: YAS_SERVICES_TAX
          value: http://yas-tax/tax
        - name: YAS_CURRENCY_UNIT
          value: VND
        - name: YAS_PRICE_INCLUDES_TAX
          value: 'false'
        - name: SERVER_PORT
          value: '80'
        - name: LOGGING_CONFIG
          value: /app-config/logback-spring.xml
        - name: JAVA_TOOL_OPTIONS
          value: -javaagent:opentelemetry-javaagent.jar
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://collector:5555
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: grpc
        - name: OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
          value: cumulative
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: service.namespace=yas-msa
        - name: OTEL_SERVICE_NAME
          value: order-service
        - name: OTEL_LOGS_EXPORTER
          value: otlp
        - name: OTEL_TRACES_EXPORTER
          value: otlp
        - name: OTEL_METRICS_EXPORTER
          value: otlp
        - name: OTEL_INSTRUMENTATION_LOGBACK-MDC_ADD-BAGGAGE
          value: 'true'
        - name: OTEL_JAVAAGENT_LOGGING
          value: application
        - name: OTEL_JAVAAGENT_ENABLED
          value: 'true'
        - name: OTEL_JAVAAGENT_DEBUG
          value: 'false'
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: yas-db-secret
              key: POSTGRES_USER
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: yas-db-secret
              key: POSTGRES_PASSWORD
