# ==========================================
# 1. INIT SCRIPT CREATE SUB DATABASE
# ==========================================
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
  namespace: yas-dev
  annotations:
    argocd.argoproj.io/sync-wave: "0"
data:
  init.sql: |
    -- Tạo DB cho Keycloak (Quản lý User/Auth)
    CREATE DATABASE keycloak;
    -- Tạo DB cho các Microservices
    CREATE DATABASE tax;
    CREATE DATABASE product;
    CREATE DATABASE cart;
    CREATE DATABASE "order"; 
    CREATE DATABASE inventory;
    CREATE DATABASE promotion;
    CREATE DATABASE customer;
    CREATE DATABASE rating;
    CREATE DATABASE payment;
    CREATE DATABASE location;
    CREATE DATABASE media;

---
# ==========================================
# 2. Ổ CỨNG LƯU TRỮ DỮ LIỆU (PERSISTENT VOLUME CLAIM)
# ==========================================
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi # 5GB storage

---
# ==========================================
# 3. DEPLOYMENT POSTGRESQL
# ==========================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: yas-db-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: yas-db-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: init-script-volume
              mountPath: /docker-entrypoint-initdb.d/init.sql
              subPath: init.sql
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
        - name: init-script-volume
          configMap:
            name: postgres-init-script

---
# ==========================================
# 4. POSTGRESQL SERVICE
# ==========================================
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432