apiVersion: apps/v1
kind: Deployment
metadata:
  name: tax
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  namespace: yas-dev
  labels:
    app: tax
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tax
  template:
    metadata:
      labels:
        app: tax
    spec:
      containers:
        - name: tax
          image: ghcr.io/nashtech-garage/yas-tax:latest # Khi cấu hình Jenkins CD, đổi dòng tag này
          ports:
            - containerPort: 80
          # Ép RAM để không chết Node
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          # Load toàn bộ biến chung từ ConfigMap
          envFrom:
            - configMapRef:
                name: yas-global-config
          # Khai báo các biến riêng của service này
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/tax"
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: "/tax"
            - name: OTEL_SERVICE_NAME
              value: "tax-service"
            # Load Password từ Secret
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: yas-db-secret
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: yas-db-secret
                  key: POSTGRES_PASSWORD