apiVersion: v1
kind: Service
metadata:
  name: tax
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  namespace: yas-dev
spec:
  type: NodePort
  selector:
    app: tax
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001